#! /usr/bin/env python
# This is the executable node. it's kept short and the code is in a moudle in src.
from test_ur5 import test_ur5
import sys

if __name__ == '__main__':
	coordinates = [float(sys.argv[1]),float(sys.argv[2]),float(sys.argv[3]),float(sys.argv[4]),float(sys.argv[5]),float(sys.argv[6])]
	exp = waypoints()
	exp.move_robot(exp.generate_plan(coordinates),float(sys.argv[7]))
